version: 2
enable-beta-ecosystems: true # Required for the pre-commit ecosystem

multi-ecosystem-groups:
  ci-deps:
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "ci-deps"
    open-pull-requests-limit: 1

  - package-ecosystem: "pre-commit"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "ci-deps"
    open-pull-requests-limit: 1
